### PR TITLE
Update orgData.json - Clemson Makerspace

### PR DESCRIPTION
**Pull request by ophilli**

### CODE REVIEW

**Comment by cbraeuning** [comment]
We don't use this file anymore, but I will merge the changes in our new view when it's in master

**Comment by ophilli** [comment]
Okay.

We also prefer to link to http://hours.cuMaker.space/ whenever discussing our hours due to their variability.

**Comment by cbraeuning** [comment]
https://github.com/MilanLund/FormatGoogleCalendar

Looks like we can use this is you make an api key for us and the calendar is public

**Comment by ophilli** [comment]
It's a Google Calendar - I know I can easily get a .ics. The Riggs Space also uses a google calendar.

I think this is the [API Reference](https://developers.google.com/google-apps/calendar/v3/reference/)

**Pull request merged**
